ServerTokens Prod
ServerSignature Off

<VirtualHost *:443>
  ServerName localhost

  DocumentRoot /var/www/html/public

  SSLEngine on
  SSLCertificateFile    /etc/ssl/localcerts/selfsigned.crt
  SSLCertificateKeyFile /etc/ssl/localcerts/selfsigned.key

  # Allow ONLY TLS 1.3
  SSLProtocol -all +TLSv1.3

  <Directory /var/www/html/public>
    AllowOverride All
    Require all granted
  </Directory>

  ErrorLog ${APACHE_LOG_DIR}/error-ssl.log
  CustomLog ${APACHE_LOG_DIR}/access-ssl.log combined

</VirtualHost>
